# Generated by Django 3.2.18 on 2023-05-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planning', '0002_alter_touristplacereviewrating_tpid'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=1000)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planning.userregistration')),
            ],
        ),
    ]
