# Generated by Django 3.2.18 on 2023-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planning', '0003_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbacks',
            field=models.CharField(default=66, max_length=1000),
            preserve_default=False,
        ),
    ]
